language: node_js
node_js:
  - "7"

cache: npm

branches:
  except:
    - gh-pages

before_install:
  - cd game/  

install:
  - npm install

script:
  - npm run lint
  - npm run test
  - npm run build

deploy:
  local-dir: ./game/dist
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
